export default {
  components: {
    wikicommitBanner: {
      // Issue #740: `review_status` is a two-valued field, which makes it
      // structurally a container for an *event* — it happened, or it has not
      // yet. What it held until now was a *claim* about the page, and a claim
      // has content, which is why the content had to be bolted on as a
      // checklist. The heading follows the field back to what it can actually
      // carry: nobody has read this page yet. That is a fact about reach, not
      // a defect in the page — and after Issue #751 the machine's own source
      // check is stated a line below, so "nobody has read it" can no longer be
      // misread as "nothing has been done to it".
      title: "Nobody has read this page yet",
      body: "Automatically generated by an LLM. It may contain inaccuracies.",
      generatedAt: "Generated:",
      generatedBy: "Model:",
      translatedAt: "Translated:",
      translatedBy: "Model:",
      reviewedBy: "Read by:",
      // Issue #739: the reviewed state adds a line rather than removing the
      // warning, so it needs a heading of its own. Wording it as "a person
      // checked this" and no further keeps it to what `reviewed` actually
      // means (Issue #723's transition table); anything stronger would be a
      // guarantee nobody made. It also carries the fact for a reviewed page
      // with no `reviewed_by` — route B pages and anything reviewed before
      // that field existed — so no name-less placeholder line is needed.
      titleReviewed: "A person has read this page",
      // Issue #751: what the machine check actually compared, stamped onto the
      // published copy of the page by convert_wikilinks.py and present on no
      // page in .wikicommit/entity/. Worded as "checked against its sources"
      // rather than "reviewed" or "verified": Pass 4 compares the page with the
      // documents it was written from and nothing else — completeness is
      // explicitly out of scope (Issue #722), and harm and conflicts with the
      // reader's own knowledge are seen by no layer at all (Issue #723).
      // Over-claiming here would repeat, in the opposite direction, the error
      // Issue #740 is correcting for `reviewed`.
      aiReviewAt: "Checked against sources:",
      aiReviewBy: "Checking model:",
      unknown: "unknown",
      reviewStatusLink: "Check this page's review status",
      reportLink: "Report something you noticed",
      // Issue #742: for a reader without a GitHub account this link lands on a
      // login wall — `/issues/new?...` redirects to `login?return_to=<the whole
      // URL>`, so the form is never shown. Issue #665 fixed the same shape of
      // error one layer up (the tracking Issue told readers to close an Issue
      // they have no permission to close); this is the layer below it. The
      // prefilled title and body do survive signing in, so the only thing left
      // to fix is that the link gives no warning — hence a statement of fact,
      // not a recruiting line. Kept out of the link label so the call to action
      // stays the loudest thing in the row (the visual-weight constraint this
      // shares with Issue #738).
      reportLinkAccountNote: "(GitHub account required)",
      reportTitlePrefix: "[Report]",
      reportBodyPage: "Page:",
      reportBodyLanguage: "Language:",
      reportBodyOriginal: "Original page:",
      // Issue #738: the two checklist items Issue #723 marked "only a person
      // can check this" reach only whoever browses the repository's Issue
      // list — in practice the operator. The reader most likely to notice the
      // harm item is usually the subject of the page, who never opens that
      // list but does read the page. This guidance rides the report link
      // instead, which every reader sees.
      reportBodyGuidanceHeading:
        "These are the kinds of problem no automated check can find. Write down any that apply (you are not being asked to go looking — only what you noticed while reading).",
      reportBodyGuidanceHarm:
        "- Anything about a real person or organization that felt overstated or too certain",
      reportBodyGuidanceKnowledge:
        "- Anything that conflicts with what you know (add a URL if you have one)",
      reportBodyGuidanceContradiction: "- Anything another page on this wiki says differently",
      // Not a closed list: a typo, a stale fact or a dead link is just as
      // welcome. Stated so the bullets above do not read as "report nothing
      // else".
      reportBodyGuidanceFooter:
        "Anything else is welcome too — typos, stale facts, broken links.",
      // The heading gives the reporter a marked place to write. `body=`
      // replaces report.md's own `## Page` / `## Problem` headings entirely, so
      // without this the prefilled body ends at the guidance and there is
      // nowhere obvious to type. The page facts above need no heading of their
      // own — each line already labels itself.
      reportBodyProblemHeading: "## Problem",
      siteSummaryPages: "Pages:",
      siteSummaryReviewed: "Read by a person:",
      siteSummaryReviewNote: "Every page is published as soon as an LLM generates it. The count above is how many a person has since read all the way through — not how much of the wiki is finished, and not a guarantee that anything is correct.",
    },
  },
}
