export default {
  components: {
    wikicommitBanner: {
      title: "This page is unreviewed",
      body: "Automatically generated by an LLM. It may contain inaccuracies.",
      generatedAt: "Generated:",
      generatedBy: "Model:",
      translatedAt: "Translated:",
      translatedBy: "Model:",
      unknown: "unknown",
      reportLink: "Report an issue",
      reportTitlePrefix: "[Report]",
      reportBodyPage: "Page:",
      reportBodyLanguage: "Language:",
      reportBodyOriginal: "Original page:",
      siteSummaryPages: "Pages:",
      siteSummaryReviewed: "Reviewed:",
      siteSummaryTheme: "Theme:",
    },
  },
}
