export default {
  components: {
    wikicommitBanner: {
      title: "This page is unreviewed",
      body: "Automatically generated by an LLM. It may contain inaccuracies.",
      generatedAt: "Generated:",
      generatedBy: "Model:",
      translatedAt: "Translated:",
      translatedBy: "Model:",
      reviewedBy: "Reviewed by:",
      unknown: "unknown",
      reviewStatusLink: "Check this page's review status",
      reportLink: "Report an issue",
      reportTitlePrefix: "[Report]",
      reportBodyPage: "Page:",
      reportBodyLanguage: "Language:",
      reportBodyOriginal: "Original page:",
      siteSummaryPages: "Pages:",
      siteSummaryReviewed: "Human-reviewed:",
      siteSummaryReviewNote: "Every page is published as soon as an LLM generates it. The count above is how many a person has since checked.",
    },
  },
}
